### ISSUE TITLE
Restrictions on device Manufacturer and model?

### ISSUE THREAD

**Issue by devlie** [Azure/iot-plugandplay-models#153]
Is there any **character set** and **length** restriction on device manufacturer and model properties in  `dtmi:azure:DeviceManagement:DeviceInformation;1`? Thanks.

**Comment by rido-min** [comment]
@devlie DTDL does not set any limits on instance properties. You should look at [this document](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins#device-twin-size ) to find which are the valid characters and size limits for IoT Hub Device Twins.

**Comment by rido-min** [comment]
@devlie does my previous reply answers your question? if so, can you close this issue?

**Comment by devlie** [comment]
@rido-min thanks! It looks like there's no meaningful limitation on manufacturer and model, and a user can theoretically set each to be 4KB. Is that correct? Are these two props used anywhere else in IoT Hub or PnP system? If we are building a solution on top of it, can we safely limit them to a shorter length?

**Comment by rido-min** [comment]
correct, it's up to the user to set the limit. IoT Hub does not makes any special treatment, those are just twin properties.

However upstream solutions like central might have a limit of what they can render. 
@sandeeppujar do you know what's the limit in central for reported properties?

**Comment by devlie** [comment]
@sandeeppujar, any idea? Thanks.

**Comment by sandeeppujar** [comment]
@devlie , IoTC adds no additional limits, they are twin properties in IoT Hub

**Comment by rido-min** [comment]
@devlie do you need anything else? Otherwise, can you close this issue?

**Comment by devlie** [comment]
Thanks for the help!
