### ISSUE TITLE
"dmr-client validate" report an error when using "humidity" semantic type and "%" unit

### ISSUE THREAD

**Issue by tmb-soc** [Azure/iot-plugandplay-models#418]
The validation of template fails when data in template are using "Humidity" semantic type and "percent" unit. 
`{
            "@id": "dtmi:com:socomec:socomecdevice:Global_0_85894;1",
            "@type": [
                "Telemetry",
                "Humidity"
            ],
            "displayName": {
                "en": "Humidity"
            },
            "name": "Global_0_85894",
            "schema": "float",
            "unit": "percent"
        },`

It is working in IOT Central:
![image](https://user-images.githubusercontent.com/97679825/149472150-410da932-f3cd-4d06-9d9b-c1c80b884750.png)

But this is rejected by dmr-client:
![image](https://user-images.githubusercontent.com/97679825/149472612-ccc65608-675e-45c6-b67c-4cb0d90833ef.png)

However, it works if the semantic type is set to "RelativeHumidity".

**Comment by rido-min** [comment]
Hi @tmb-soc

Thanks for reporting this issue, this seems an issue in Central rather than DMR.

I'm adding @sandeeppujar from the central team to take note before closing.

**Comment by rido-min** [comment]
Closing as this is not related to this repo. If still require a resolution I'd suggest filing an issue in the Azure IoT Central docs
