### ISSUE TITLE
Template not taken into account in IOT Central

### ISSUE THREAD

**Issue by tmb-soc** [Azure/iot-plugandplay-models#419]
It seems that **iot-plugandplay-models/dtmi/com/socomec/socomecgateway-1.json** template is not taken into account in IOT Central when device is requesting `dtmi:com:socomec:socomecgateway;1`.

However, no problem with **iot-plugandplay-models/dtmi/com/socomec/socomecdevice-1.json** when device is requesting `dtmi:com:socomec:socomecdevice;1`.

![image](https://user-images.githubusercontent.com/97679825/149764736-eb4508a3-e697-430f-90be-e2132a56aab7.png)

**Comment by tmb-soc** [comment]
The problem is not what you are describing. Let me explain in details:

1. I start with an empty device list in the IOT Central application. I take the connection settings from **Administration/Device connection** (SAS-IoT-Devices) and I put the parameters in my gateway.
2. The gateway creates itself in the device list with the "group enrollment" method. It send its model ID **socomecgateway-1**, but it is not recognized.
3. The gateway creates the devices in the same way with the **socomecdevice-1** model ID. It is correctly recognized and apply in the device list of the IOT Central application.

**Comment by rido-min** [comment]
Closing as this is not related to this repo. If still require a resolution I'd suggest filing an issue in the Azure IoT Central docs
