### ISSUE TITLE
what is the procedure to rename the telemetry name in the already published model?

### ISSUE THREAD

**Issue by RavichandranRajamanickam** [Azure/iot-plugandplay-models#43]
what is the procedure to rename the telemetry name in the already published model? 

_Originally posted by @RavichandranRajamanickam in https://github.com/Azure/iot-plugandplay-models/pull/42#issuecomment-723970032_

**Comment by rido-min** [comment]
Hey @RavichandranRajamanickam 

All interfaces in this repository are meant to be *immutable*, this means you must create a new version to update.

This requirement is documented in the [docs](https://docs.microsoft.com/en-us/azure/iot-pnp/concepts-model-repository) and in the [PR requirements](https://github.com/Azure/iot-plugandplay-models/blob/main/pr-reqs.md#deletions-and-edits).

Can you close PR #42 and create a new one with the new versions?

Thanks for your submissions
Rido
